name: Build and Test Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Run tests inside container
        run: docker run --rm ghcr.io/${{ github.repository }}:latest pytest test.py