name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Tag image for Docker Hub
        run: docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

      - name: Run Docker container
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
