name: Build, Push and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/SofiaBurma/dockerized-app:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker image
        run: docker pull ghcr.io/SofiaBurma/dockerized-app:latest

      - name: Run tests inside container
        run: docker run ghcr.io/SofiaBurma/dockerized-app:latest